version: '3'
services:

  website:
    build: .
    restart: always
    volumes:
      - ./:/var/www/html/
    expose:
      - 80
    environment:
      - "VIRTUAL_HOST=www.m-k.io,m-k.io"
      - "LETSENCRYPT_HOST=m-k.io"
      - "LETSENCRYPT_EMAIL=hello@m-k.io"

networks:
  default:
    external:
      name: nginx-net
